<a href="https://colab.research.google.com/github/subham129/Machine-Learning-/blob/main/Cross_Validation_Scores.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.datasets import load_digits

digits = load_digits()

In [9]:
import pandas as pd
data_df = pd.DataFrame(digits.data, columns=digits.feature_names if hasattr(digits, 'feature_names') else [f'pixel_{i}' for i in range(digits.data.shape[1])])

target_df = pd.DataFrame(digits.target, columns=['target'])
digits_df = pd.concat([data_df, target_df], axis=1)
print(digits_df.head())


   pixel_0_0  pixel_0_1  pixel_0_2  pixel_0_3  pixel_0_4  pixel_0_5  \
0        0.0        0.0        5.0       13.0        9.0        1.0   
1        0.0        0.0        0.0       12.0       13.0        5.0   
2        0.0        0.0        0.0        4.0       15.0       12.0   
3        0.0        0.0        7.0       15.0       13.0        1.0   
4        0.0        0.0        0.0        1.0       11.0        0.0   

   pixel_0_6  pixel_0_7  pixel_1_0  pixel_1_1  ...  pixel_6_7  pixel_7_0  \
0        0.0        0.0        0.0        0.0  ...        0.0        0.0   
1        0.0        0.0        0.0        0.0  ...        0.0        0.0   
2        0.0        0.0        0.0        0.0  ...        0.0        0.0   
3        0.0        0.0        0.0        8.0  ...        0.0        0.0   
4        0.0        0.0        0.0        0.0  ...        0.0        0.0   

   pixel_7_1  pixel_7_2  pixel_7_3  pixel_7_4  pixel_7_5  pixel_7_6  \
0        0.0        6.0       13.0       10.0

In [10]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(digits.data, digits.target, test_size=0.2)

In [32]:
lr = LogisticRegression()
svc = SVC()
rf = RandomForestClassifier(n_estimators=40)

In [12]:
lr.fit(x_train, y_train)
svc.fit(x_train, y_train)
rf.fit(x_train, y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


RandomForestClassifier()

In [13]:
pred1 = lr.predict(x_test)
pred2 = svc.predict(x_test)
pred3 = rf.predict(x_test)

In [14]:
from sklearn.metrics import accuracy_score

In [15]:
print(f'Logistic Regression Accuracy: {accuracy_score(y_test, pred1)}')
print(f'SVC Accuracy: {accuracy_score(y_test, pred2)}')
print(f'Random Forest Accuracy: {accuracy_score(y_test, pred3)}')

Logistic Regression Accuracy: 0.9583333333333334
SVC Accuracy: 0.9944444444444445
Random Forest Accuracy: 0.9916666666666667


In [19]:
from sklearn.model_selection import KFold

In [21]:
kf = KFold(n_splits=3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [33]:
def score(model,x_train,x_test,y_train,y_test):
    model.fit(x_train,y_train)
    pred = model.predict(x_test)
    return accuracy_score(pred,y_test)

In [34]:
score(rf,x_train,x_test,y_train,y_test)

0.9232053422370617

In [24]:
from sklearn.model_selection import StratifiedKFold

In [25]:
folds = StratifiedKFold(n_splits=3)

In [26]:
scores_lr = []
scores_svc = []
scores_rf = []

In [27]:
for train_index,test_index in kf.split(digits.data):
  x_train,x_test,y_train,y_test = digits.data[train_index],digits.data[test_index],digits.target[train_index],digits.target[test_index]
  scores_lr.append(score(lr,x_train,x_test,y_train,y_test))
  scores_svc.append(score(svc,x_train,x_test,y_train,y_test))
  scores_rf.append(score(rf,x_train,x_test,y_train,y_test))


/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _c

In [28]:
scores_lr

[0.9232053422370617, 0.9415692821368948, 0.9148580968280468]

In [30]:
scores_svc

[0.9666110183639399, 0.9816360601001669, 0.9549248747913188]

In [31]:
scores_rf

[0.9332220367278798, 0.9515859766277128, 0.9415692821368948]

In [35]:
from sklearn.model_selection import cross_val_score

In [37]:
 cross_val_score(rf,digits.data,digits.target)

array([0.93888889, 0.88333333, 0.95264624, 0.95543175, 0.92479109])

In [38]:
cross_val_score(svc,digits.data,digits.target)

array([0.96111111, 0.94444444, 0.98328691, 0.98885794, 0.93871866])

In [39]:
cross_val_score(lr,digits.data,digits.target,scoring='accuracy')

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _c

array([0.92222222, 0.86944444, 0.94150418, 0.93871866, 0.89693593])